require("spec/spec_helper")
local C = require("engine/conditions")

describe("eval_atom", function()
  it("true for nil / empty / 'True'", function()
    assert.is_true(C.eval_atom(nil, {}))
    assert.is_true(C.eval_atom("", {}))
    assert.is_true(C.eval_atom("True", {}))
  end)
  it("compares each operator numerically", function()
    local v = { v_x = "3" }
    assert.is_true(C.eval_atom("v_x > 2", v))
    assert.is_false(C.eval_atom("v_x > 3", v))
    assert.is_true(C.eval_atom("v_x >= 3", v))
    assert.is_true(C.eval_atom("v_x == 3", v))
    assert.is_true(C.eval_atom("v_x != 4", v))
    assert.is_true(C.eval_atom("v_x < 4", v))
    assert.is_true(C.eval_atom("v_x <= 3", v))
  end)
  it("treats an unset variable as 0", function()
    assert.is_true(C.eval_atom("v_missing == 0", {}))
    assert.is_false(C.eval_atom("v_missing > 0", {}))
  end)
  it("handles snake_case identifiers (Lua %w gotcha)", function()
    assert.is_true(C.eval_atom("v_ancient_languages > 2", { v_ancient_languages = "3" }))
  end)
  it("returns nil and records a failure for a malformed atom", function()
    C.failures = {}
    assert.is_nil(C.eval_atom("False", {}))
    assert.are.equal(1, #C.failures)
  end)
end)

describe("eval", function()
  it("nil dnf is unconditional true", function()
    assert.is_true(C.eval(nil, {}))
  end)
  it("OR of ANDs", function()
    local v = { v_a = "1", v_b = "0", v_c = "9" }
    assert.is_true(C.eval({ { "v_a > 5" }, { "v_c > 5" } }, v))
    assert.is_false(C.eval({ { "v_a > 5" }, { "v_b > 5" } }, v))
    assert.is_true(C.eval({ { "v_a == 1", "v_b == 0" } }, v))
    assert.is_false(C.eval({ { "v_a == 1", "v_b == 1" } }, v))
  end)
  it("an empty AND clause is true (JS .every on [])", function()
    assert.is_true(C.eval({ {} }, {}))
  end)
end)
