require("spec/spec_helper")
local parser = require("engine/parser")

describe("_match_set", function()
  it("matches a plain set", function()
    local n, v, c = parser._match_set("set(v_is_dead, 1)")
    assert.are.equal("v_is_dead", n); assert.are.equal("1", v); assert.is_nil(c)
  end)
  it("matches a relative set with a condition", function()
    local n, v, c = parser._match_set("set(v_ac_x, +3) if (v_a > 1)")
    assert.are.equal("v_ac_x", n); assert.are.equal("+3", v)
    assert.are.equal("(v_a > 1)", c)
  end)
  it("returns nil for a non-set line", function()
    assert.is_nil(parser._match_set("He drew set(the) blade"))
  end)
  it("errors on a multi-digit literal (02 R3)", function()
    assert.has_error(function() parser._match_set("set(v_x, 12)") end)
  end)
end)

describe("_match_achievement", function()
  it("captures text and variable", function()
    local t, v = parser._match_achievement('achievement("A message in the sky",v_ac_ch1_coward)')
    assert.are.equal("A message in the sky", t)
    assert.are.equal("v_ac_ch1_coward", v)
  end)
end)

describe("_match_choice", function()
  it("parses target, set-vars and a divert", function()
    local c = parser._match_choice('choice("Excited", Ch1-Intro2, v_ch1_intro_feeling = 1, v_current_scene = Ch1-Intro2)')
    assert.are.equal("Excited", c.text)
    assert.are.equal("Ch1-Intro2", c.target)
    assert.are.equal("1", c.set_vars.v_ch1_intro_feeling)
    assert.are.equal("Ch1-Intro2", c.set_vars.v_current_scene)
    assert.is_nil(c.special)
  end)
  it("handles doubled-quote spoken labels (02 F-06)", function()
    local c = parser._match_choice('choice(""I see no reason to hide."", Ch1-Dave2, v_current_scene = Ch1-Dave2)')
    assert.are.equal('"I see no reason to hide."', c.text)
    assert.are.equal("Ch1-Dave2", c.target)
  end)
  it("captures special: and a trailing condition", function()
    local c = parser._match_choice('choice("Load game", , , special:saves) if (v_a > 0)')
    assert.are.equal("saves", c.special)
    assert.are.same({ { "v_a > 0" } }, c.conditions)
  end)
end)

describe("_match_if", function()
  it("captures the condition up to the last paren", function()
    assert.are.equal("v_ch1_intro_feeling == 1", parser._match_if("#if(v_ch1_intro_feeling == 1)"))
  end)
end)
