require("spec/spec_helper")
local specials = require("engine/specials")

describe("specials", function()
  it("default scene", function()
    assert.are.equal("Ch1-Intro1", specials.DEFAULT_SCENE)
  end)
  it("suppresses stat checks in the Average-Joe reveal", function()
    assert.is_true(specials.suppress_stat_checks("B3-Ch04a-Introduction2"))
    assert.is_false(specials.suppress_stat_checks("Ch1-Intro1"))
  end)
  it("appends the consolation prize when the flag is set", function()
    assert.are.same({}, specials.extra_achievements({}))
    local extra = specials.extra_achievements({ v_ac_b3_ch9_prize = "1" })
    assert.are.equal(1, #extra)
    assert.are.equal("v_ac_b3_ch9_prize", extra[1].variable)
  end)
end)
