require("spec/spec_helper")
local specials = require("engine/specials")

describe("specials", function()
  it("default scene", function()
    assert.are.equal("Ch1-Intro1", specials.DEFAULT_SCENE)
  end)
  it("suppresses stat checks in the Average-Joe reveal", function()
    assert.is_true(specials.suppress_stat_checks("B3-Ch04a-Introduction2"))
    assert.is_false(specials.suppress_stat_checks("Ch1-Intro1"))
  end)
  it("appends the consolation prize when the flag is set", function()
    assert.are.same({}, specials.extra_achievements({}))
    local extra = specials.extra_achievements({ v_ac_b3_ch9_prize = "1" })
    assert.are.equal(1, #extra)
    assert.are.equal("v_ac_b3_ch9_prize", extra[1].variable)
  end)
  it("hides the device-lock stat-check text only on B3-Ch01a-Crossbow", function()
    assert.is_true(specials.HIDE_DEVICE_LOCK_TEXT["B3-Ch01a-Crossbow"])
    assert.is_nil(specials.HIDE_DEVICE_LOCK_TEXT["B3-Ch01a-Intro"])
  end)

  describe("stats-screen gates", function()
    it("maximized only at Ch6-Eiden-vs-dragon with the flag", function()
      assert.is_true(specials.maximized_stats("Ch6-Eiden-vs-dragon", { v_maximized_stats_used = "1" }))
      assert.is_false(specials.maximized_stats("Ch6-Eiden-vs-dragon", {}))
      assert.is_false(specials.maximized_stats("Ch2-Intro", { v_maximized_stats_used = "1" }))
    end)
    it("magic rows when v_b3_ch11_magic is set (incl. \"0\")", function()
      assert.is_true(specials.stats_show_magic_rows({ v_b3_ch11_magic = "2" }))
      assert.is_true(specials.stats_show_magic_rows({ v_b3_ch11_magic = "0" }))
      assert.is_false(specials.stats_show_magic_rows({}))
      assert.is_false(specials.stats_show_magic_rows({ v_b3_ch11_magic = "" }))
    end)
    it("book-3 rows only for book 3, chapter >= 4, with a letter suffix", function()
      assert.is_true(specials.stats_show_book3_rows("B3-Ch04a-Introduction"))
      assert.is_true(specials.stats_show_book3_rows("B3-Ch12a-Bored"))
      assert.is_false(specials.stats_show_book3_rows("B3-Ch03a-Foo"))
      assert.is_false(specials.stats_show_book3_rows("B3-Ch4-Foo"))   -- no [a-c]
      assert.is_false(specials.stats_show_book3_rows("B2-Ch04a-Foo"))
      assert.is_false(specials.stats_show_book3_rows("Ch11a-Stats-spent1"))
    end)
  end)
end)
