require("spec/spec_helper")
local Store = require("engine/store")

describe("Store", function()
  it("get/set round-trips strings", function()
    local s = Store.new()
    s:set("v_x", "3")
    assert.are.equal("3", s:get("v_x"))
    assert.is_nil(s:get("v_missing"))
  end)

  it("resolves +N / -N on write", function()
    local s = Store.new({ v_c = "2" })
    s:set("v_c", "+3")
    assert.are.equal("5", s:get("v_c"))
    s:set("v_c", "-1")
    assert.are.equal("4", s:get("v_c"))
  end)

  it("+N against an unset variable starts from 0", function()
    local s = Store.new()
    s:set("v_new", "+2")
    assert.are.equal("2", s:get("v_new"))
  end)

  it("freezes a v_ac_* flag once it reaches 2 (any incoming value)", function()
    local s = Store.new({ v_ac_x = "2" })
    s:set("v_ac_x", "1")
    assert.are.equal("2", s:get("v_ac_x"))
    s:set("v_ac_x", "3")
    assert.are.equal("2", s:get("v_ac_x"))
    s:set("v_ac_x", "+5")
    assert.are.equal("2", s:get("v_ac_x"))
  end)

  it("does not freeze a non-v_ac_ variable at 2", function()
    local s = Store.new({ v_ch1_show_yourself = "2" })
    s:set("v_ch1_show_yourself", "1")
    assert.are.equal("1", s:get("v_ch1_show_yourself"))
  end)

  it("triggers the consolation prize at exactly 5 (special case #12)", function()
    -- Seeded at 4 to bypass the v_ac_ freeze (which otherwise caps this counter
    -- at 2, exactly as magium-dev does). `storeItem`: data[key] == 5.
    local s = Store.new({ v_ac_b3_ch9_consolation = "4" })
    s:set("v_ac_b3_ch9_consolation", "+1")
    assert.are.equal("5", s:get("v_ac_b3_ch9_consolation"))
    assert.are.equal("1", s:get("v_ac_b3_ch9_prize"))
  end)

  it("view is a detached copy", function()
    local s = Store.new({ v_a = "1" })
    local v = s:view()
    v.v_a = "999"
    assert.are.equal("1", s:get("v_a"))
  end)

  it("snapshot / restore round-trips", function()
    local s = Store.new({ v_a = "1", v_b = "2" })
    local snap = s:snapshot()
    s:set("v_a", "9")
    s:restore(snap)
    assert.are.equal("1", s:get("v_a"))
  end)
end)
